// 共通データ — ポートフォリオ全体で使用
window.PORTFOLIO_DATA = {
  profile: {
    nameJa: "竹森 達也",
    nameEn: "Tatsuya Takemori",
    title: "ハードウェアエンジニア / テクニカルディレクター",
    titleEn: "Hardware Engineer / Technical Director",
    affiliation: "Abstract Engine",
    degree: "博士（工学）",
    born: "1993, 京都",
    bio: "1993年京都生まれ。京都大学工学部物理工学科を卒業し、京都大学大学院工学研究科機械理工学専攻を修了、2021年に同専攻にて博士（工学）を取得し、京都大学メカトロニクス研究室にて研究員を務めた。日本学術振興会特別研究員DC1。学位研究では複雑環境におけるヘビ型ロボットの制御に取り組んだ。並行して研究室内のチームを率いて多機能レスキューロボットを開発し、ロボカップ世界大会2019レスキュー実機リーグで総合優勝を果たすなど活躍。それらの成果から2018年度日本機械学会業績賞（研究）、国際レスキューシステム研究機構2019年度競基弘技術貢献賞、2020年度システム制御情報学会学会賞奨励賞、平成29年度京都大学総長賞、令和元年度京都大学総長賞などを受賞。\n\n2022年からアブストラクトエンジンに所属し、ハードウェアエンジニア・テクニカルディレクターとして研究開発・実装を担う。Rhizomatiks作品にも参加するほか、アーティストとのコラボレーションも行う。メカ、電子回路、制御工学、ソフトウェアの総合的な設計開発を得意とし、アート・エンターテイメント分野でのロボティクス技術を活かした企画やディレクションも行う。主な参加作品は「Shadow Up」シリーズ、「\"Syn : 身体感覚の新たな地平\" by Rhizomatiks × ELEVENPLAY」、「Perfume Disco-Graphy 25年の軌跡と奇跡」、SHIBUYA SKY 常設の球状LED照明「PixOrb / NEBULA」、岸裕真とのコラボレーション作品「xoxo-skeleton」「平行森林」 など。",
    bioShort: "ロボティクス技術を、アートとエンターテイメントの現場へ。京都大学でヘビ型ロボット・レスキューロボットの研究に従事し、博士号取得・国際大会優勝を経て、現在はアブストラクトエンジンでハードウェアエンジニア・テクニカルディレクターとして活動。",
    links: [
      { label: "X / Twitter", url: "https://x.com/rbbtake" },
      { label: "Instagram", url: "https://www.instagram.com/takemori.tatsuya/" },
      { label: "Blog (旧)", url: "https://tattatatakemori.hatenablog.com/" },
    ],
  },

  // 制作物 — 時系列（新しい順）
  // 制作物 — 時系列（新しい順）
  works: [
    {
      id: "parallel-forests",
      title: "岸裕真 \"平行森林 Parallel Forests\"",
      year: "2026.03",
      role: "テクニカルディレクション / ハードウェアエンジニア",
      tags: ["Art", "Exhibition", "100 devices"],
      desc: "夜の森を舞台に植物の生体データから音と光を生成するインスタレーション。全体のシステム設計とハードウェア面のテクニカルディレクションを担当。LLM推論用NPU搭載のBIデバイス100台について、サブ基板の新規開発・筐体設計・量産・設置、デバイス間ネットワークの構築などを行った。",
      link: "https://abstractengine.com/work/parallel-forests/",
      thumbnail: "https://abstractengine.com/wp-content/uploads/2026/04/A1T1761_2.jpg",
    },
    {
      id: "xoxo",
      title: "岸裕真 \"xoxo-skeleton\"",
      year: "2026.02",
      role: "テクニカルディレクション / ハードウェアエンジニア",
      tags: ["Art", "Robot Arm", "Sensor"],
      desc: "AIに制御される外骨格デバイス。肋骨型什器の各骨の先端に並ぶ24枚のセンサー基板を新規設計し、装着者の両手首と首を操る長尺ロボットアーム3本（QDDモーター駆動の冗長機構）の機構・制御回路・制御システム一式を開発。全体のテクニカルディレクションも担当。",
      link: "https://abstractengine.com/work/%e5%b2%b8%e8%a3%95%e7%9c%9f-xoxo-skeleton/",
      thumbnail: "https://abstractengine.com/wp-content/uploads/2026/04/hero.jpg",
    },
    {
      id: "pixorb",
      title: "PixOrb / NEBULA",
      year: "2025.07",
      role: "立案 / 開発 / 制作",
      tags: ["Lighting", "Permanent", "渋谷スカイ"],
      desc: "球体表面に高密度LEDを配置した独自開発の球状灯具「PixOrb」。プロジェクトの立案、灯具本体のハードウェア開発までを担当した。本照明は渋谷スカイの常設インスタレーション「NEBULA」として実装され四季を通して活用されている。",
      link: "https://prtimes.jp/main/html/rd/p/000000037.000015546.html",
      thumbnail: "https://prcdn.freetls.fastly.net/release_image/15546/37/15546-37-8c6368470f08ad40cdd3bf626a1b76e8-1920x1281.jpg?width=1950&height=1350&quality=85%2C65&format=jpeg&auto=webp&fit=bounds&bg-color=fff",
    },
    {
      id: "coro",
      title: "CORO",
      year: "2025.03",
      role: "自律移動制御",
      tags: ["Furniture", "Autonomous"],
      desc: "株式会社コトブキとのコラボレーションによる、人と共生する移動するファニチャー。屋外環境下での自律移動アルゴリズムと制御システムの設計・実装を担当した。",
      link: "https://townscape.kotobuki.co.jp/news/2025/20250910_002178.html",
      thumbnail: "https://townscape.kotobuki.co.jp/news/images/2e4356868abfe2b938508fcf322967e8bc951ce3.png",
    },
    {
      id: "shadowup",
      title: "シャドウアップ™ シリーズ",
      year: "2024.12–",
      role: "テクニカルディレクション / 立案・開発",
      tags: ["Installation", "Lighting", "Permanent"],
      desc: "独自開発のステレオライト®システム（特許出願中）により、影や光が空中に浮き上がるアナログ立体映像が立ち現れる特殊な体験。プロジェクトの企画立案、コアシステムの研究開発、各会場への実装までを横断的に担当。様々な形態で作品を発表している。",
      link: "https://abstractengine.com/work/shadowup/",
      thumbnail: "https://abstractengine.com/wp-content/uploads/2025/05/ShadowUp_AE-web_banner.jpg",
    },
    {
      id: "shadowup-kochi",
      title: "シャドウアップ™ 高知城",
      year: "2024.12",
      role: "テクニカルディレクション / インスタレーション設計・制作",
      tags: ["Installation", "Heritage"],
      desc: "重要文化財・高知城を舞台にしたシャドウアップ™の大型展開（2024.12–2025.01）。企画段階から、全体のテクニカルディレクション、およびインスタレーションのための装置の設計と開発、設置まで担当した。",
      link: "https://kochipark.jp/kochijyo/shadowup-kochi/",
      thumbnail: "https://kochipark.jp/kochijyo/wp-content/themes/kochipark/assets/img/shadowup/SHADOWUP_STAGE.avif",
    },
    {
      id: "perfume",
      title: "Perfume Disco-Graphy 25年の軌跡と奇跡",
      year: "2024.08",
      role: "オブジェ設計 / キャリブレーションシステム",
      tags: ["Exhibition", "Music", "TOKYO NODE"],
      desc: "TOKYO NODEで開催されたPerfume 25周年記念展「We are Perfume GALLERY-C」。展示空間の中核となるキネティック・オブジェのデザイン、および会場全体の映像位置合わせを行うキャリブレーションシステムの開発に関わった。",
      link: "https://www.tokyonode.jp/sp/perfume/",
      thumbnail: "https://www.tokyonode.jp/sp/perfume/img/kv_pc_nologo.jpg",
    },
    {
      id: "honda-xr",
      title: "Honda XR Mobility Experience",
      year: "2024.03",
      role: "Plan / UNI-ONE linked control program",
      tags: ["XR", "Mobility", "SXSW2024"],
      desc: "SXSW2024（オースティン）に出展されたHondaのXRモビリティ体験。企画プランニングに参加し、UNI-ONEならではのXRの仕掛けを考案。XR体験と同期してパーソナルモビリティ「UNI-ONE」を動かすための連動制御プログラムの開発を担当した。",
      link: "https://abstractengine.com/work/honda-xr-mobility-experience-sxsw2024/",
      thumbnail: "https://abstractengine.com/wp-content/uploads/2026/01/UNI-ONE_thumb.jpg",
    },
    {
      id: "laser-ropes",
      title: "Laser Ropes -prototype case1-",
      year: "2024.03",
      role: "文化庁クリエイター支援事業 / 個人制作",
      tags: ["Prototype", "Laser"],
      desc: "文化庁メディア芸術クリエイター育成支援事業の採択を受けて個人で制作したプロトタイプ。レーザー光を「ロープ」のように扱い、空間に張り渡された光線の形状をリアルタイムに変調する独自の表現装置を開発。企画・機構・制御まで全工程を担当。",
      link: "https://www.youtube.com/watch?v=uud-kyyP0G8",
      thumbnail: "https://i.ytimg.com/vi/uud-kyyP0G8/hqdefault.jpg",
    },
    {
      id: "anrealage",
      title: "ANREALAGE パリコレクション 2024A/W",
      year: "2024.02",
      role: "技術協力 / ハードウェアエンジニア",
      tags: ["Fashion", "Paris"],
      desc: "ANREALAGEのパリコレクション 2024 A/Wに技術協力。オブジェクトを浮遊させるための機構設計・制作を行った。",
      link: "https://casabrutus.com/categories/fashion/397659",
      thumbnail: "https://casabrutus.com/_next/image?url=https%3A%2F%2Fwp2022.casabrutus.com%2Fwp-content%2Fuploads%2F2025%2F02%2F0228doraemon019_1312.jpg&w=1920&q=75",
    },
    {
      id: "moving-wings",
      title: "動く翼",
      year: "2024.01",
      role: "特殊衣装 設計・制作・納品",
      tags: ["Costume", "Mechanism"],
      desc: "羽ばたき動作を行う可動式の翼衣装。リモコン操作により様々なポーズ・モーションが可能。持ち運びや着脱を考慮した軽量・コンパクトな機構として設計・制作した。",
      link: "https://twitter.com/i/status/1832051795243532409",
      thumbnail: "assets/wings.png",
    },
    {
      id: "syn",
      title: "Syn : 身体感覚の新たな地平 by Rhizomatiks × ELEVENPLAY",
      year: "2023.10",
      role: "Rhizomatiks × ELEVENPLAY / ハードウェア・装置開発",
      tags: ["Performance", "Dance"],
      desc: "RhizomatiksとELEVENPLAYによる、身体と機械が協奏する没入型パフォーマンス作品。本作のために開発した「ステレオライト」と「波紋制御システム」の2つの装置開発を担当した。",
      link: "https://rhizomatiks.com/work/syn-by-rhizomatiks-elevenplay/",
      thumbnail: "https://rhizomatiks.com/wp-content/uploads/2023/12/DSC08553-1200x800.jpg",
    },
    {
      id: "in-spire",
      title: "三田真一展 in-Spire – Breath of life – 呼吸",
      year: "2023.06",
      role: "技術協力 / 装置設計",
      tags: ["Exhibition"],
      desc: "スタイリスト三田真一による個展。音象限儀（木工芸 ＋ 製缶 ＋ Rhizomatiks ＋ NF）においてフィルムを動かすためのからくりの開発・実装を担当。",
      link: "https://keidai.art/lookback/971",
    },
    {
      id: "nosaj",
      title: "Nosaj Thing x Daito Manabe light sync device by Rhizomatiks",
      year: "2022.08",
      role: "LED Robot Control System Design & Production",
      tags: ["Art Festival", "Installation"],
      desc: "アートフェスnorm Art & Design Festival 2022にて初披露されたライゾマティックスの新作インスタレーション。LEDディスプレイを搭載したロボット群の自律移動制御システムの設計・制作を担当した。",
      link: "https://rhizomatiks.com/work/light-sync-device_w-osaka/",
    },
  ],

  // 京都大学時代の研究・制作（research-driven works）
  researchWorks: [
    {
      id: "snake",
      title: "ヘビ型ロボット",
      period: "2014–2021",
      role: "学位研究 / 単独開発",
      desc: "ヘビ型ロボットの動作設計と制御を学位研究として遂行。世界初となるヘビ型ロボットによるはしご登りに成功し、険しい不整地の移動、配管上のフランジ乗り越えなど多様な動作を実現。IEEE Transactions on Robotics をはじめとする主要国際ジャーナルで筆頭論文を複数発表。",
      tags: ["PhD", "Snake Robot", "World-First"],
      media: [
        { kind: "youtube", id: "w89D4oRrrSQ", title: "はしご登りデモ" },
        { kind: "youtube", id: "t2UYf6OzyyI", title: "不整地・配管上動作デモ" },
        { kind: "link", url: "https://www.gizmodo.jp/2018/10/ladder-climbing-robot-snake-freaks.html", title: "GIZMODO Japan — はしごを登るヘビ型ロボット", host: "gizmodo.jp" },
      ],
    },
    {
      id: "fuhga",
      title: "ロボカップレスキュー",
      period: "2017–2021",
      role: "チームリーダー / SHINOBI",
      desc: "多機能クローラ型レスキューロボット FUHGA シリーズを開発。研究室内チーム SHINOBI を率いて毎年一からロボットを設計・製作。FUHGA2 は World Robot Summit 2018 STM 部門で経済産業大臣賞（賞金1000万円）を受賞、改良機は RoboCup 世界大会 2019 で日本チーム14年ぶりの総合優勝。後継機 FUHGA3 は RoboCup 2021 Virtual で Best in Class を複数受賞。",
      tags: ["Rescue", "Team Lead", "World Champion"],
      media: [
        { kind: "youtube", id: "IIPH8K0KFhE", title: "FUHGAシリーズ デモ" },
        { kind: "link", url: "https://www.t.kyoto-u.ac.jp/publicity/no74/news/2aives", title: "京都大学工学部ニュース No.74 — RoboCup世界大会2019優勝", host: "t.kyoto-u.ac.jp" },
        { kind: "link", url: "https://www.kyoto-u.ac.jp/kurenai/202103/spirit/robot.html", title: "京都大学広報誌『紅萌』 — レスキューロボットチーム SHINOBI", host: "kyoto-u.ac.jp" },
      ],
    },
    {
      id: "mimebot",
      title: "Mimebot",
      period: "2014–2016",
      role: "ロボット開発",
      desc: "球体ディスプレイを乗せた移動ロボット。ベース移動と球体表示の同期/非同期によって「滑り」「転がり」など多様な動きの錯視を演出可能。国際会議 MoMM 2016（Singapore）と国際ジャーナル IJPCC 2017 で発表し、Highly Commended Award を受賞。",
      tags: ["HCI", "Sphere", "Entertainment"],
      media: [
        { kind: "youtube", id: "N6OWAsTIqzk", title: "Mimebot デモ動画" },
        { kind: "link", url: "https://doi.org/10.1108/IJPCC-01-2017-0006", title: "IJPCC 2017 — Mimebot: Spherical Robot Visually Imitating a Rolling Sphere", host: "doi.org" },
      ],
    },
    {
      id: "robotrace",
      title: "個人ロボコン（ロボトレース・キャチロボなど）",
      period: "2012–2016",
      role: "個人製作",
      desc: "学部時代を中心にロボトレース・キャチロボなどの個人ロボコンに参加。代表作「OmnimO」は全方位フォトリフレクタ配列により向きを変えずにラインを追従し、一周目でコース記憶・二周目で加減速制御を行うアルゴリズムを実装。多数の特別賞を受賞。",
      tags: ["Robotrace", "Self-made"],
      media: [
        { kind: "youtube", id: "lMzBxPXLrYo", title: "OmnimO 走行デモ" },
        { kind: "link", url: "https://tattatatakemori.hatenablog.com/", title: "個人ロボコン製作記（ブログアーカイブ）", host: "hatenablog.com" },
      ],
    },
  ],

  // 学術雑誌
  publications: [
    { authors: "Tatsuya Takemori, Motoyasu Tanaka, Fumitoshi Matsuno", title: "Adaptive Helical Rolling of a Snake Robot to a Straight Pipe With Irregular Cross-Sectional Shape", venue: "IEEE Transactions on Robotics", vol: "vol.39, no.1, pp.437–451", year: "2023", url: "https://ieeexplore.ieee.org/document/9834040" },
    { authors: "T. Takanashi, M. Nakajima, T. Takemori, M. Tanaka", title: "Obstacle-Aided Locomotion of a Snake Robot Using Piecewise Helixes", venue: "IEEE Robotics and Automation Letters", vol: "vol.7, no.4, pp.10542–10549", year: "2022", url: "https://ieeexplore.ieee.org/document/9844258" },
    { authors: "B. A. Elsayed, T. Takemori, M. Tanaka, F. Matsuno", title: "Mobile Manipulation Using a Snake Robot in a Helical Gait", venue: "IEEE/ASME Transactions on Mechatronics", year: "2021", url: "https://ieeexplore.ieee.org/document/9562974" },
    { authors: "M. Inazawa, T. Takemori, M. Tanaka, F. Matsuno", title: "Unified Approach to the Motion Design for a Snake Robot Negotiating Complicated Pipe Structures", venue: "Frontiers in Robotics and AI", year: "2021", url: "https://doi.org/10.3389/frobt.2021.629368" },
    { authors: "Tatsuya Takemori, Motoyasu Tanaka, Fumitoshi Matsuno", title: "Hoop-Passing Motion for a Snake Robot to Realize Motion Transition Across Different Environments", venue: "IEEE Transactions on Robotics", vol: "vol.37, no.5, pp.1696–1711", year: "2021", url: "https://ieeexplore.ieee.org/document/9387411" },
    { authors: "T. Takemori, M. Miyake, T. Hirai, et al.", title: "Development of the multifunctional rescue robot FUHGA2 and evaluation at the World Robot Summit 2018", venue: "Advanced Robotics", vol: "vol.34, no.2, pp.119–131", year: "2020", url: "https://doi.org/10.1080/01691864.2019.1697751" },
    { authors: "Tatsuya Takemori, Motoyasu Tanaka, Fumitoshi Matsuno", title: "Gait Design for a Snake Robot by Connecting Curve Segments and Experimental Demonstration", venue: "IEEE Transactions on Robotics", vol: "vol.34, no.5, pp.1384–1391", year: "2018", url: "https://doi.org/10.1109/TRO.2018.2830346" },
    { authors: "S. Tsuchida, T. Takemori, T. Terada, M. Tsukamoto", title: "Mimebot: Spherical Robot Visually Imitating a Rolling Sphere", venue: "International Journal of Pervasive Computing and Communications", vol: "vol.13, no.1", year: "2017", url: "https://doi.org/10.1108/IJPCC-01-2017-0006" },
    { authors: "土田修平, 竹森達也, 寺田努, 塚本昌彦", title: "回転移動を模したテクスチャ表示機能をもつ球体型移動ロボット", venue: "情報処理学会論文誌", vol: "vol.57, no.12, pp.140–149", year: "2016" },
  ],

  books: [
    { authors: "F. Matsuno, T. Kamegawa, W. Qi, T. Takemori, M. Tanaka, M. Nakajima et al.", title: "Disaster Robotics – Results from the ImPACT Tough Robotics Challenge – （Section: Development of Tough Snake Robot Systems）", year: "2019", url: "https://link.springer.com/book/10.1007/978-3-030-05321-5" },
    { authors: "有泉亮, 竹森達也", title: "ロボット制御学ハンドブック 第16章5節「連続体モデルと制御」", venue: "近代科学社", year: "2017" },
  ],

  internationalConferences: [
    { authors: "T. Takemori et al.", title: "Development of FUHGA2, FUHGA3 and YAGURA for Inspection and Rescue activity and evaluation in World Robot Summit 2020", venue: "AROB 27th'22", year: "2022" },
    { authors: "X. Wang, T. Takemori et al.", title: "Autonomous Navigation of Mobile Manipulator FUHGA3 and Evaluation in RoboCupRescue 2021", venue: "AROB 27th'22", year: "2022" },
    { authors: "M. Inazawa, T. Takemori, M. Tanaka, F. Matsuno", title: "Motion Design for a Snake Robot Negotiating Complicated Pipe Structures of a Constant Diameter", venue: "ICRA 2020", year: "2020" },
    { authors: "T. Takemori, M. Tanaka, F. Matsuno", title: "Ladder Climbing with a Snake Robot", venue: "IROS 2018, Madrid", year: "2018" },
    { authors: "T. Takemori, M. Tanaka, F. Matsuno", title: "Gait Design for a Snake Robot to Climb a Ladder", venue: "SWARM 2017, Kyoto", year: "2017" },
    { authors: "S. Tsuchida, T. Takemori, T. Terada, M. Tsukamoto", title: "Mimebot: Sphere-shaped Mobile Robot Imitating Rotational Movement", venue: "MoMM 2016, Singapore", year: "2016" },
    { authors: "T. Takemori, M. Tanaka, F. Matsuno", title: "Gait Design of a Snake Robot by Connecting Simple Shapes", venue: "IEEE SSRR 2016, Lausanne", year: "2016" },
  ],

  patents: [
    { id: "JP2019-195864", title: "関節機構および多関節機構", number: "特開2019-195864" },
  ],

  grants: [
    { recipient: "竹森達也", title: "JSPS科研費 特別研究員奨励費（DC1）「全身に触覚を持つヘビ型ロボットによる複雑環境上での自律移動と作業の制御」", period: "2018–2020" },
    { recipient: "土田修平, 友近圭汰, 竹森達也", title: "JST 大学発新産業創出プログラム(START) 技術シーズ選抜育成プロジェクト〔ロボティクス分野〕", period: "2015", note: "300万円、応募40件中18件採択" },
  ],

  awards: [
    { year: "2021", title: "IEEE RAS JJC Student Author Award", venue: "IROS2021", category: "学会賞" },
    { year: "2021", title: "International Young Authors Award", venue: "計測自動制御学会 IROS2021", category: "学会賞" },
    { year: "2021", title: "Best Student Paper Award", venue: "DARS-SWARM 2021", category: "学会賞", co: "B. Elsayed, T. Takemori, F. Matsuno" },
    { year: "2020", title: "システム制御情報学会 学会賞 奨励賞", category: "学会賞" },
    { year: "2019", title: "競基弘技術貢献賞", venue: "国際レスキューシステム研究機構", category: "学会賞" },
    { year: "2018", title: "日本機械学会業績賞（研究）", category: "学会賞" },
    { year: "2018", title: "International Journal of Pervasive Computing and Communications, Highly Commended Award", category: "学会賞" },
    { year: "2018", title: "SCI'18 学生発表賞", category: "学会賞" },
    { year: "2017", title: "SI2017 優秀講演賞", category: "学会賞" },
    { year: "2016", title: "SI2016 優秀講演賞", category: "学会賞" },

    { year: "2019", title: "京都大学 工学研究科長賞", category: "学内表彰" },
    { year: "2019", title: "京都大学 総長賞", category: "学内表彰" },
    { year: "2018", title: "京都大学 工学研究科長賞", category: "学内表彰" },
    { year: "—", title: "京都大学 工学研究科 馬詰研究奨励賞", category: "学内表彰" },
    { year: "2017", title: "京都大学 工学研究科長賞", category: "学内表彰" },
    { year: "2017", title: "京都大学 総長賞", category: "学内表彰" },
    { year: "2016", title: "吉田卒業研究・論文賞", category: "学内表彰" },

    { year: "2020", title: "World Robot Summit 2020 インフラ・災害対応 プラント災害予防チャレンジ 準優勝（NEDO理事長賞）／日本ロボット学会特別賞", category: "国際大会" },
    { year: "2021", title: "RoboCup世界大会2021 Rescue Robot League — Best in Class AutoMobility / Best in Class Inspect", category: "国際大会" },
    { year: "2019", title: "RoboCup世界大会2019 Rescue Robot League 優勝（日本チーム14年ぶり）／Best in Class Dexterity", category: "国際大会" },
    { year: "2018", title: "World Robot Summit 2018 STM部門 優勝（経済産業大臣賞・賞金1000万円）／日本ロボット学会賞", category: "国際大会" },
    { year: "2017", title: "RoboCup世界大会2017 Rescue Robot League — Best in Class Dexterity / Best in Class Small Robot", category: "国際大会" },

    { year: "2019", title: "RoboCup JAPAN OPEN 2019 レスキューロボット実機リーグ 優勝（3連覇）／Dexterity / Mobility / 計測自動制御学会賞", category: "日本大会" },
    { year: "2018", title: "RoboCup JAPAN OPEN 2018 レスキューロボット実機リーグ 優勝（2連覇）／Best in Class Dexterity", category: "日本大会" },
    { year: "2017", title: "RoboCup JAPAN OPEN 2017 レスキューロボット実機リーグ 優勝／Best in Class Dexterity / 計測自動制御学会賞", category: "日本大会" },
    { year: "2016", title: "RoboCup JAPAN OPEN 2016 レスキューロボット実機リーグ Best in Class Autonomy", category: "日本大会" },
  ],
};
